apiVersion: v1
kind: Namespace
metadata:
  name: cnb-springboot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: cnb-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cnb-springboot
  template:
    metadata:
      labels:
        app: cnb-springboot
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port:  "8080"
    spec:
      containers:
        - image: alexandreroman/cnb-springboot-kpack
          name: app
          resources:
            limits:
              memory: 1Gi
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 60
            periodSeconds: 2
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: cnb-springboot
  labels:
    app: cnb-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: cnb-springboot
