---
apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: cnb-javawar
  namespace: kpack-builders
spec:
  tag: alexandreroman/cnb-javawar-kpack
  serviceAccount: kpack-service-account
  builder:
    name: custom-java-builder
    kind: CustomBuilder
  cacheSize: "2Gi"
  source:
    git:
      url: https://github.com/alexandreroman/cnb-javawar.git
      revision: testing
