apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: cnb-nodejs
  namespace: kpack-builders
spec:
  tag: alexandreroman/cnb-nodejs-kpack
  serviceAccount: kpack-service-account
  builder:
    name: custom-nodejs-builder
    kind: CustomBuilder
  cacheSize: "2Gi"
  source:
    git:
      url: https://github.com/alexandreroman/cnb-nodejs.git
      revision: testing
