---
apiVersion: experimental.kpack.pivotal.io/v1alpha1
kind: Store
metadata:
  name: custom-java-store
  namespace: kpack-builders
spec:
  sources:
  - image: cloudfoundry/cnb:0.0.81-bionic
---
apiVersion: experimental.kpack.pivotal.io/v1alpha1
kind: CustomBuilder
metadata:
  name: custom-java-builder
  namespace: kpack-builders
spec:
  tag: alexandreroman/kpack-custom-java-builder
  serviceAccount: kpack-service-account
  stack: bionic-stack
  store: custom-java-store
  order:
  - group:
    - id: org.cloudfoundry.openjdk
    - id: org.cloudfoundry.buildsystem
      optional: true
    - id: org.cloudfoundry.jvmapplication
      optional: true
    - id: org.cloudfoundry.tomcat
      optional: true
    - id: org.cloudfoundry.springboot
      optional: true
    - id: org.cloudfoundry.distzip
      optional: true
